integration tests removed from cicd

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -20,50 +20,50 @@ jobs:
       - name: Run unit tests
         run: make test-unit
 
-  integration-tests:
-    name: Run Integration Tests
-    runs-on: ubuntu-latest
+  # integration-tests:
+  #   name: Run Integration Tests
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v3
       
-      - name: Copy .env
-        run: cp .env.test.example .env.test
+  #     - name: Copy .env
+  #       run: cp .env.test.example .env.test
 
-      - name: Start containers
-        run: docker compose --env-file .env.test -f docker-compose.test.yml  up -d
+  #     - name: Start containers
+  #       run: docker compose --env-file .env.test -f docker-compose.test.yml  up -d
 
-      - name: Wait for Postgres to be healthy
-        run: |
-          for i in {1..20}; do
-            STATUS=$(docker inspect --format='{{.State.Health.Status}}' tarot-postgres-test)
-            echo "⏳ DB health status: $STATUS"
-            if [ "$STATUS" = "healthy" ]; then
-              echo "✅ DB is healthy"
-              break
-            fi
-            sleep 2
-          done
+  #     - name: Wait for Postgres to be healthy
+  #       run: |
+  #         for i in {1..20}; do
+  #           STATUS=$(docker inspect --format='{{.State.Health.Status}}' tarot-postgres-test)
+  #           echo "⏳ DB health status: $STATUS"
+  #           if [ "$STATUS" = "healthy" ]; then
+  #             echo "✅ DB is healthy"
+  #             break
+  #           fi
+  #           sleep 2
+  #         done
 
-          if [ "$STATUS" != "healthy" ]; then
-            echo "❌ DB failed to become healthy"
-            docker logs tarot-postgres-test
-            exit 1
-          fi
+  #         if [ "$STATUS" != "healthy" ]; then
+  #           echo "❌ DB failed to become healthy"
+  #           docker logs tarot-postgres-test
+  #           exit 1
+  #         fi
 
-      - name: Run Integration Tests
-        run: go test -v ./tests/integration/...
+  #     - name: Run Integration Tests
+  #       run: go test -v ./tests/integration/...
 
-      - name: Stop test containers
-        if: always()
-        run: docker compose -f docker-compose.test.yml down
+  #     - name: Stop test containers
+  #       if: always()
+  #       run: docker compose -f docker-compose.test.yml down
 
 
   deploy:
     name: Deploy Release
     if: startsWith(github.ref, 'refs/tags/v') 
-    needs: [unit-tests, integration-tests]
+    needs: [unit-tests]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
